
SELECT COUNT(*)
FROM "RESULTS";

SELECT MIN("POINTS"), AVG("POINTS"), MAX("POINTS"), SUM("POINTS")
FROM "RESULTS";

SELECT *
FROM "RESULTS"
WHERE "CAT" = 'H';

SELECT MIN("POINTS"), AVG("POINTS"), MAX("POINTS"), SUM("POINTS")
FROM "RESULTS"
WHERE "CAT" = 'H';

