
SELECT *
FROM "STUDENTS" "S" LEFT OUTER JOIN "RESULTS" "R"
ON ("S"."SID" = "R"."SID");

SELECT "S"."LAST", "R"."POINTS"
FROM "STUDENTS" "S" LEFT OUTER JOIN "RESULTS" "R"
ON ("S"."SID" = "R"."SID");

