
SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = "STUDENTS"."SID"
);

SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = 101
);

SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = 102
);

SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = 103
);

SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = 104
);

SELECT "FIRST", "LAST"
FROM "STUDENTS"
WHERE NOT EXISTS (
    SELECT *
    FROM "RESULTS"
    WHERE "RESULTS"."SID" = "STUDENTS"."SID"
);

